### ISSUE TITLE
[BUG?] 通知类型改为「QQ通知」后，通知的透明背景会被模糊处理

### ISSUE THREAD

**Issue by bling-yshs** [mo-jinran/More-Materials#10]
![image](https://github.com/user-attachments/assets/bdda062c-72ce-4424-8659-27e0916e6dee)

**右下角的透明背景被模糊了**
![image](https://github.com/user-attachments/assets/ef6bafa1-2ee8-4f85-9cd6-8323dfdd0318)

![image](https://github.com/user-attachments/assets/4b7f0457-db9d-4661-973c-c46691d9ae01)

**Comment by mo-jinran** [comment]
这个，逻辑上是对的，「QQ通知」也是一个浏览器窗口可以设置模糊效果

**Comment by bling-yshs** [comment]
> 这个，逻辑上是对的，「QQ通知」也是一个浏览器窗口可以设置模糊效果

确实，但是这一坨看着好难受... 有什么办法可以让这个通知的透明背景不模糊么？比如改通知的某个css？
