### ISSUE TITLE
新版qq使用该插件后再用截屏功能会导致截屏全白

### ISSUE THREAD

**Issue by MinadukiShizuku** [mo-jinran/More-Materials#14]

**Comment by rainbowflesh** [comment]
[window.setBackgroundMaterial(config.win32.material);](https://github.com/mo-jinran/More-Materials/blob/fe71f8efcdb9a4f3c30dd2971da4906ca792e695/src/main.js#L39)
作者这样实现的更多材质, 会让截图的窗体也被盖上, 这里需要找到截图程序新建的窗体类然后判断跳过.

**Comment by mo-jinran** [comment]
早在7月17号修了，你需要更新
