### ISSUE TITLE
QQ有两个最小化 出现win原版顶栏

### ISSUE THREAD

**Issue by MoeSnowyFox** [mo-jinran/More-Materials#5]
<img width="628" alt="image" src="https://github.com/mo-jinran/More-Materials/assets/156929726/42d0db17-ca59-4e71-b533-c233f411b6ac">
电脑版本:
版本	Windows 11 专业工作站版 Insider Preview
版本	22H2
安装日期	‎2023/‎7/‎5
操作系统版本	25236.1010
体验	Windows Feature Experience Pack 1000.25236.1010.0
QQ版本:
<img width="468" alt="image" src="https://github.com/mo-jinran/More-Materials/assets/156929726/2a304ecd-02d1-47d7-8f3c-926cc2fdc2e7">

**Comment by mo-jinran** [comment]
这就是窗体边框
