### ISSUE TITLE
9.9.12-25765失效

### ISSUE THREAD

**Issue by huoyan1231** [mo-jinran/More-Materials#9]

**Comment by mo-jinran** [comment]
还没失效，一些主题还没适配新版，导致此插件的背景效果不会显示

**Comment by huoyan1231** [comment]
> 还没失效，一些主题还没适配新版，导致此插件的背景效果不会显示

![image](https://github.com/user-attachments/assets/a81eacef-bdaa-4f38-ab29-31d795c05208)
只开了这一个插件也没效果，是我这哪里有问题吗

**Comment by mo-jinran** [comment]
你还需要安装第三方兼容的主题，但是那些主题还没更新

**Comment by huoyan1231** [comment]
> 你还需要安装第三方兼容的主题，但是那些主题还没更新

这样 了解了
